### ISSUE TITLE
Any plans on a build release?

### ISSUE THREAD

**Issue by FreezyChan** [tattn/VRMKit#4]
Just wondering if there will be a build release, like a .ipa file or something.

**Comment by tattn** [comment]
This repository contains an example project.
You can open `VRMKit.xcodeproj` and run the app of `Example` scheme 👍

**Comment by FreezyChan** [comment]
Sorry, i don't have a mac

**Comment by tattn** [comment]
I have no plans for release so far...
You can also see example app on the web: https://appetize.io/app/y64jp9pb85f3txmezmx66ezbkc?device=iphone6s&scale=75&orientation=portrait&osVersion=11.4
But this site is very slow🐢

**Comment by tattn** [comment]
I'll close this issue. If you have some problems, you can reopen the issue.
